name: manual-syndication
on: [workflow_dispatch]
jobs:
    cron:
        runs-on: ubuntu-latest
        steps:
            - name: manual-syndication
              run: |
                  curl -X POST 'https://coryd.dev/api/syndicate' \
                  -H 'Authorization: Bearer ${{ secrets.VERCEL_SYNDICATE_KEY }}'
